language: python
install:
- pip install poetry
- poetry install

matrix:
  include:
    - name: "black"
      python: 3.6
      script:
        - poetry run black --check --config pyproject.toml .
    - name: "mypy"
      python: 3.6
      script:
        - poetry run mypy --config-file setup.cfg .
    - name: "flake8"
      python: 3.6
      script:
        - poetry run flake8 --config --settings-path setup.cfg .
    - name: "isort"
      python: 3.6
      script:
        - poetry run isort --check --settings-path setup.cfg .
    - name: "pytest"
      python: 3.6
      script:
        - poetry run python -m pytest .
